name: movies_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.3
  http: ^0.13.5
  fade_shimmer: ^2.0.1
  flutter_dotenv: ^5.0.2
  tmdb_api: ^2.1.4
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  firebase_database: ^10.0.9
  firebase_auth_web: ^5.2.4
  cloud_firestore: ^4.3.1
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  rename: ^2.1.1
  contactus: ^1.2.0
  provider: ^6.0.5
  rating_bar: ^0.2.0
  flutter_rating_bar: ^4.0.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"    

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/logooo.png

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Light.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.otf
